from fastapi import APIRouter, Query
from fastapi.responses import StreamingResponse
from typing import Optional
from app.services.campaign_recommender_ml import recommend_campaigns_ml
from app.services.campaign_planner import launch_campaign
from app.services.auto_segmentation import run_segmentation
from app.ml.continuous_analyzer import get_behavior_analyzer
from app.services.campaign_tracker import get_campaign_tracker
from app.services.ai_message_generator import get_message_generator
from app.ml.campaign_metrics_estimator import get_campaign_estimator
from app.services.ai_service import get_ai_service
from app.monitoring.llm_observability import get_recent_llm_calls

router = APIRouter(
    tags=["AI"]
)


@router.post("/pipeline/{member_id}")
async def run_agentic_pipeline(member_id: str, prompt: Optional[str] = None):
    """
    Run the LangGraph agent pipeline for a member and return proposal + reasoning trace.
    """
    ai_service = get_ai_service()
    return await ai_service.run_member_pipeline(member_id=member_id, prompt=prompt)


@router.get("/stream/{member_id}")
async def stream_agentic_pipeline(member_id: str, prompt: Optional[str] = None):
    """
    Stream LangGraph node execution events over SSE for real-time AI reasoning UX.
    """
    ai_service = get_ai_service()
    return StreamingResponse(
        ai_service.stream_member_pipeline(member_id=member_id, prompt=prompt),
        media_type="text/event-stream",
        headers={
            "Cache-Control": "no-cache",
            "Connection": "keep-alive",
            "X-Accel-Buffering": "no",
        },
    )


@router.get("/metrics")
async def get_ai_metrics(limit: int = Query(100, ge=1, le=100)):
    """
    Return recent LLM/LangGraph node execution telemetry.
    """
    return {"items": get_recent_llm_calls(limit=limit)}


@router.get("/recommendations")
async def get_recommendations():
    """
    Returns AI-generated campaign recommendations using ML models.
    Includes detailed cost estimates and participation rates.
    Frontend-safe: always returns a list.
    """
    return await recommend_campaigns_ml()


@router.post("/launch")
async def launch_ai_campaign(payload: dict):
    """
    Launch campaign generated by AI with tracking
    """
    campaign_id = launch_campaign(payload)

    # Start tracking the campaign
    tracker = get_campaign_tracker()
    await tracker.track_campaign_execution(campaign_id, payload)

    return {
        "status": "launched",
        "campaign_id": campaign_id
    }


@router.get("/segmentation/run")
async def run_auto_segmentation(force: bool = Query(False)):
    """
    Run automatic customer segmentation using ML

    Args:
        force: Force re-segmentation even if recently run

    Returns:
        Segmentation results with distribution
    """
    return await run_segmentation(force=force)


@router.get("/behavior/analyze")
async def analyze_behavior(days: int = Query(30, ge=7, le=365)):
    """
    Analyze recent customer behavior patterns

    Args:
        days: Number of days to analyze (7-365)

    Returns:
        Behavior analysis with changes and alerts
    """
    analyzer = get_behavior_analyzer()
    return await analyzer.analyze_recent_behavior(days=days)


@router.get("/behavior/alerts")
async def get_behavior_alerts():
    """
    Get actionable alerts based on behavior analysis

    Returns:
        List of alerts for marketing team
    """
    analyzer = get_behavior_analyzer()
    return await analyzer.generate_behavior_alerts()


@router.get("/campaign/{campaign_id}/metrics")
async def get_campaign_metrics(campaign_id: str):
    """
    Get real-time metrics for an active campaign

    Args:
        campaign_id: Campaign identifier

    Returns:
        Live campaign performance metrics
    """
    tracker = get_campaign_tracker()
    return await tracker.get_live_metrics(campaign_id)


@router.post("/campaign/{campaign_id}/status")
async def update_campaign_status(campaign_id: str, status: str):
    """
    Update campaign status (pause, resume, complete)

    Args:
        campaign_id: Campaign identifier
        status: New status (active, paused, completed)

    Returns:
        Update confirmation
    """
    tracker = get_campaign_tracker()
    return await tracker.update_campaign_status(campaign_id, status)


@router.post("/message/generate")
async def generate_campaign_message(request: dict):
    """
    Generate AI-powered campaign message

    Args:
        request: Message parameters (segment, campaign_type, behavior, channel, brand_name, incentive)

    Returns:
        Generated message with subject and body
    """
    generator = get_message_generator()
    return await generator.generate_campaign_message(
        segment=request.get("segment", "general"),
        campaign_type=request.get("campaign_type", "general"),
        behavior=request.get("behavior", "general_activity"),
        channel=request.get("channel", "email"),
        brand_name=request.get("brand_name", "Loyalty Pro"),
        incentive=request.get("incentive")
    )


@router.post("/campaign/estimate")
async def estimate_campaign_metrics(request: dict):
    """
    Get detailed cost and performance estimates for a campaign

    Args:
        request: Campaign parameters (segment, channel, target_count, campaign_type, incentive_value)

    Returns:
        Complete campaign estimate with costs, ROI, participation
    """
    estimator = get_campaign_estimator()
    return estimator.generate_full_campaign_estimate(
        segment=request.get("segment", "general"),
        channel=request.get("channel", "email"),
        target_count=request.get("target_count", 100),
        campaign_type=request.get("campaign_type", "general"),
        incentive_value=request.get("incentive_value", 0.0)
    )
